config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :categories do
    resources :tasks
  end

  delete '/categories/:category_id/tasks/:id' => 'pages#destroy', as: 'delete_task'

  root to: 'pages#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    has_many :tasks
    belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, 
                    length: { maximum: 255 }
    validates :description, presence: true
    belongs_to :category

    delegate :user, to: :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  
  devise :database_authenticatable, :registerable, :validatable
  has_many :categories, dependent: :destroy
  has_many :tasks, through: :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base    
    def after_sign_out_path_for(resource)
        new_user_session_path
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :get_user_id

    def index
        @categories = @user_id.categories
    end

    def show
        @category = @user_id.categories.find(params[:id])
    end

    def new
        @category = @user_id.categories.new        
    end

    def create
        @category = @user_id.categories.new(category_params)

        if @category.save
            redirect_to categories_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @category = @user_id.categories.find(params[:id])
    end

    def update
        @category = @user_id.categories.find(params[:id])

        if @category.update(category_params)
            redirect_to categories_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @category = @user_id.categories.find(params[:id])
        @category.destroy
        redirect_to categories_path, status: :see_other
    end

    private

    def get_user_id
        @user_id = User.find(current_user.id)
    end

    def category_params
        params.require(:category).permit(:name)
    end
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :authenticate_user!
    before_action :get_tasks

    private

    def get_tasks 
        @date = Date.today.to_s
        @category = User.find(current_user.id).categories
        @tasks_today = []
        @category.each do |category|
            category.tasks.each do |task|
                @tasks_today.push(task) if task.deadline.to_s.include?(@date)
            end
        end
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :get_category
    
    def index
        @tasks = @category.tasks
    end

    def show
        @task = @category.tasks.find(params[:id])
    end

    def new
        @task = @category.tasks.build
    end

    def create
        @task = @category.tasks.build(task_params)

        if @task.save
            redirect_to category_tasks_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @task = @category.tasks.find(params[:id])
    end

    def update
        @task = @category.tasks.find(params[:id])

        if @task.update(task_params)
            redirect_to category_tasks_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @task = @category.tasks.find(params[:id])
        @task.delete

        redirect_to category_tasks_path
    end

    private

    def get_category
        @user_id = User.find(current_user.id)
        @category = @user_id.categories.find(params[:category_id])
    end

    def task_params
        params.require(:task).permit(:name, :description, :deadline, :category_id)
    end
end 

app/controllers/user_controller.rb
class UsersController < ApplicationController
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<div class="container main-c">
  <div class="row border mb-3">
    <div class="col">
      <h1>Edit Category: <%= @category.name %></h1>
      <%= link_to "Home Page", root_path, class:"btn btn-link no-pad-sides" %> >
      <%= link_to "Categories", categories_path, class:"btn btn-link no-pad-sides" %> >
      <%= link_to "#{@category.name}", category_path(@category.id), class:"btn btn-link no-pad-sides" %>     
      <a class="btn no-pad-sides rm-style"> > Edit</a>     
    </div>
  </div>
  <div class="row">
    <%= form_for @category do |f| %>
      <p>
      <% if @category.errors.any? %>
        <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      </p>
        
      <div class="field form-group mb-3">
        <%= f.label :name, class:"form-label", value:"Updated Category Name" %>
        <%= f.text_field :name, class:"form-control" %>
      </div>
        
        
      <div class="actions mb-3">
        <%= f.submit "Update Category", class:"btn btn-primary" %>
      </div>

      <%= link_to "Back", :back, class:"btn btn-primary" %>
        
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container main-c">
    <div class="row border mb-3">
        <div class="col">
            <h1>Categories</h1>
            <%= link_to "Home Page", root_path, class:"btn btn-link no-pad-sides" %>
            <a class="btn no-pad-sides rm-style"> > Categories</a>          
        </div>
    </div>    
    <div class="row">
        <%= link_to "Create New Category", new_category_path, data:{turbo_frame: "modal"}, class:"btn btn-secondary mb-3" %>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">Category Name</th>
                    <th colspan="4" scope="col" style="text-align: center">Options</th>
                </tr>
            </thead>
            <tbody>                
                <% @categories.each do |category| %>    
                    <tr>
                        <td><%= category.name %></td>
                        <td><%= link_to "View", category_path(category.id), class:"btn btn-success" %></td>
                        <td><%= link_to "Tasks", category_tasks_path(category.id), class:"btn btn-primary" %></td>
                        <td><%= link_to "Edit", edit_category_path(category.id), class:"btn btn-warning" %>  </td>
                        <td><%= button_to "Delete", {:action => 'destroy', :id => category.id }, :method => :delete, class:"btn btn-danger" %></td>               
                    </tr>  
                <% end %>
            </tbody>
        </table>
    </div>    
</div>

app/views/categories/new.html.erb
<div class="container main-c">
  <div class="row border mb-3">
    <div class="col">
      <h1>Create New Category</h1>
      <%= link_to "Home Page", root_path, class:"btn btn-link no-pad-sides" %> >
      <%= link_to "Categories", categories_path, class:"btn btn-link no-pad-sides" %>
      <a class="btn no-pad-sides rm-style"> > Create Category</a> 
    </div>
  </div>
  <div class="row">
    <%= form_with(model: @category) do |f| %>

      <p>
        <% if @category.errors.any? %>
          <ul>
            <% @category.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </p>
      
      <div class="field form-group mb-3">
          <%= f.label :name, class:"form-label", value:"Category Name" %>
          <%= f.text_field :name, class:"form-control" %>
      </div>
      
      <div class="field form-group mb-3">
        <%= f.submit "Create Category", class:"btn btn-primary" %>
      </div>
      <%= link_to "Back", :back, class:"btn btn-primary" %>
    <% end %>
    
  </div>
</div>
    

app/views/categories/show.html.erb
<div class="container main-c">
    <div class="row border mb-3">
        <div class="col">
            <h1>Category Details</h1>
            <%= link_to "Home Page", root_path, class:"btn btn-link no-pad-sides" %> >
            <%= link_to "Categories", categories_path, class:"btn btn-link no-pad-sides" %>
            <a class="btn no-pad-sides rm-style"> > <%= @category.name %></a>            
        </div>              
    </div>
    <div class="row">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">Category Name</th>
                    <th scope="col">Category Id</th>
                    <th scope="col">Creation Date</th>
                    <th scope="col">Last Update</th>
                    <th scope="col" colspan="3">Options</th>
                </tr>
            </thead> 
            <tbody>                
                <tr>
                    <td><%= @category.name %></td>
                    <td><%= @category.id %></td>
                    <td><%= @category.created_at %></td>
                    <td><%= @category.updated_at %></td>
                    <td><%= link_to "Tasks", category_tasks_path(@category.id), class:"btn btn-primary" %></td>
                    <td><%= link_to "Edit", edit_category_path(@category.id), class:"btn btn-warning" %></td>
                    <td><%= button_to "Delete", {:action => 'destroy', :id => @category.id }, :method => :delete, class:"btn btn-danger" %></td>   
                </tr>
            </tbody>
        </table>
    </div>  
    <%= link_to "Back", :back, class:"btn btn-primary" %>
</div>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>  
  <%- flash.each do |name, msg| -%>
    <div class="container">
      <% if msg == "Invalid Email or password." %>
        <div class="alert alert-danger mb-3" role="alert">
          <%= content_tag :div, msg, id: "flash_#{name}" %>
        </div>
      <% else %>
        <div class="alert alert-success mb-3" role="alert">
          <%= content_tag :div, msg, id: "flash_#{name}" %>
        </div>
      <% end %>
    </div>
  <%- end -%>
  <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container main-c">
    <div class="row border mb-3">
        <div class="col">
            <h1>Home Page</h1>
            <%= link_to "Go to Categories", categories_path, class:"btn btn-primary mb-3" %>
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class:"btn btn-light mb-3" %>
        </div>
    </div>
    <div class="row">
        <% if @tasks_today.count != 0 %>
            <h2>Pending tasks for today:</h2>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Task Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Description</th>
                        <th scope="col">Deadline</th>
                        <th scope="col" colspan="2">Options</th>
                    </tr>
                </thead> 
                <tbody>   
                    <% @tasks_today.each do |task| %>
                        <tr>
                            <td><%= task.name %></td>
                            <td><%= @category.find(task.category_id).name %></td>
                            <td><%= task.description %></td>
                            <td><%= task.deadline.to_s[0..9] %></td>
                            <td><%= link_to "Edit", edit_category_task_path(task.category_id, task.id), class:"btn btn-warning" %></td>
                            <td><%= button_to "Delete", delete_task_path(task.category_id, task.id), :method => :delete, class:"btn btn-danger" %></td>  
                        </tr>
                    <% end %>  
                </tbody>
            </table>
        <% else %>
            <h2>You have no pending task for today!</h2>
        <% end %>        
    </div>  
</div>

app/views/tasks/edit.html.erb
<div class="container main-c">
  <div class="row border mb-3">
    <div class="col">
      <h1>Edit Task: <%= @task.name %></h1>
      <%= link_to "Home Page", root_path, class:"btn btn-link no-pad-sides" %> >
      <%= link_to "Categories", categories_path, class:"btn btn-link no-pad-sides" %> >
      <%= link_to "#{@category.name}", category_path(@category.id), class:"btn btn-link no-pad-sides" %> >
      <%= link_to "Tasks", category_tasks_path(@category.id), class:"btn btn-link no-pad-sides" %> >
      <%= link_to "#{@task.name}", category_task_path(@category.id, @task.id), class:"btn btn-link no-pad-sides" %>
      <a class="btn no-pad-sides rm-style"> > Edit</a>           
    </div>
  </div>
  <div class="row">
    <%= form_with(model: [@category, @task]) do |f| %>
    
      <p>
        <% if @task.errors.any? %>
        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
        <% end %>
      </p>
        
      <div class="field form-group mb-3">
      <%= f.label :name, class:"form-label", value:"Updated Category Name" %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
      
    <div class="field form-group mb-3">
      <%= f.label :description, class:"form-label", value:"Updated Description" %>
      <%= f.text_field :description, class:"form-control" %>
    </div>
      
    <div class="field form-group mb-3">
      <%= f.label :deadline, class:"form-label", value:"Updated Deadline" %><br/>
      <%= f.date_field :deadline, min: Date.today, class:"form-control" %>
    </div>
      
    <div class="actions mb-3">
        <%= f.submit "Update Task", class:"btn btn-primary" %>
    </div> 
    <%= link_to "Back", :back, class:"btn btn-primary" %>
    <% end %>
  </div>
</div>
        

app/views/tasks/index.html.erb
<div class="container main-c">
    <div class="row border mb-3">
        <div class="col">
            <h1>Tasks for <%= @category.name %></h1>
            <%= link_to "Home Page", root_path, class:"btn btn-link no-pad-sides" %> >
            <%= link_to "Categories", categories_path, class:"btn btn-link no-pad-sides" %> >
            <%= link_to "#{@category.name}", category_path(@category.id), class:"btn btn-link no-pad-sides" %>     
            <a class="btn no-pad-sides rm-style"> > Tasks</a>   
        </div>
    </div>

    <div class="row">
        <%= link_to "Create New Task", new_category_task_path, class:"btn btn-secondary mb-3" %>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">Task Name</th>                        
                    <th colspan="3" scope="col" style="text-align: center">Options</th>
                </tr>
            </thead>
            <tbody>                
                <% @tasks.each do |task| %>    
                    <tr>
                        <td><%= task.name %></td>
                        <td><%= link_to "View", category_task_path(@category.id, task.id), class:"btn btn-success" %></td>
                        <td><%= link_to "Edit", edit_category_task_path(@category.id, task.id), class:"btn btn-warning" %></td>
                        <td><%= button_to "Delete", {:action => 'destroy', :id => task.id }, :method => :delete, class:"btn btn-danger" %></td>               
                    </tr>  
                <% end %>
            </tbody>
        </table>
    </div>    
</div>

app/views/tasks/new.html.erb
<div class="container main-c">
  <div class="row border mb-3">
    <div class="col">
      <h1>Create New Task for <%= @category.name %></h1>
      <%= link_to "Home Page", root_path, class:"btn btn-link no-pad-sides" %> >
      <%= link_to "Categories", categories_path, class:"btn btn-link no-pad-sides" %> >
      <%= link_to "#{@category.name}", category_path(@category.id), class:"btn btn-link no-pad-sides" %> >
      <%= link_to "Tasks", category_tasks_path(@category.id), class:"btn btn-link no-pad-sides" %>
      <a class="btn no-pad-sides rm-style"> > Create Task</a> 
    </div>
  </div>
  <%= form_with(model: [@category, @task]) do |f| %>
    
    <p>
      <% if @task.errors.any? %>
        <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
          </ul>
          <% end %>
          </p>  
    
          <div class="field form-group mb-3">
          <%= f.label :name, class:"form-label", value:"Task Name" %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
          
        <div class="field form-group mb-3">
          <%= f.label :description, class:"form-label", value:"Description" %>
          <%= f.text_field :description, class:"form-control" %>
        </div>
          
        <div class="field form-group mb-3">
          <%= f.label :deadline, class:"form-label", value:"Deadline" %>
          <%= f.date_field :deadline, min: Date.today, class:"form-control" %>
        </div>
          
        <div class="actions mb-3">
            <%= f.submit "Create Task", class:"btn btn-primary" %>
        </div> 
        <%= link_to "Back", :back, class:"btn btn-primary" %>
    <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container main-c">
    <div class="row border mb-3">
        <div class="col">
            <h1>Task Details</h1>
            <%= link_to "Home Page", root_path, class:"btn btn-link no-pad-sides" %> >
            <%= link_to "Categories", categories_path, class:"btn btn-link no-pad-sides" %> >
            <%= link_to "#{@category.name}", category_path(@category.id), class:"btn btn-link no-pad-sides" %> >
            <%= link_to "Tasks", category_tasks_path(@category.id), class:"btn btn-link no-pad-sides" %>
            <a class="btn no-pad-sides rm-style"> > <%= @task.name %></a>             
        </div>              
    </div>
    <div class="row">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">Task Name</th>
                    <th scope="col">Category</th>
                    <th scope="col">Description</th>
                    <th scope="col">Deadline</th>
                    <th scope="col" colspan="2">Options</th>
                </tr>
            </thead> 
            <tbody>                
                <tr>
                    <td><%= @task.name %></td>
                    <td><%= @category.name %></td>
                    <td><%= @task.description %></td>
                    <td><%= @task.deadline %></td>
                    <td><%= link_to "Edit", edit_category_task_path(@category.id, @task.id), class:"btn btn-warning" %></td>
                    <td><%= button_to "Delete", {:action => 'destroy', :id => @task.id }, :method => :delete, class:"btn btn-danger" %></td>   
                </tr>
            </tbody>
        </table>
    </div>  
    <%= link_to "Back", :back, class:"btn btn-primary" %>
</div>
